services:
  - type: web
    name: love-and-laugh-web
    env: python
    region: global    # or your region
    plan: free        # or whatever tier you choose
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn event_ticketing.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: event_ticketing.settings
    staticPublish:
      - path: static/
    autoDeploy: true
